### ISSUE TITLE
Error: Could not build wheels for pandas, matplotlib and netifaces

### ISSUE THREAD

**Issue by RosadoJ** [microsoft/ics-forensics-tools#5]
When running requirements.txt command I get the following error Error: Could not build wheels for pandas, matplotlib and netifaces attached is the screenshot. I have the required .net version and python version installed.
![Screenshot 2023-12-08 210243](https://github.com/microsoft/ics-forensics-tools/assets/141789595/11646bd8-0edd-4cb7-8022-45a5bc48257d)

**Comment by maayan-sh** [comment]
Hi,
What command exactly did you execute? If you have installed Python >= 3.9 and the Microsoft Visual C++ 14.0, the requirements should get installed properly.

**Comment by RosadoJ** [comment]
I ran this command pip install -r requirements.txt

I do have the latest python version and MS Visual C++ 14.0. But I will double check.

**Comment by RosadoJ** [comment]
Yeaup I do have those 👆installed.

**Comment by erithacus-rubecula** [comment]
In case this is still a problem for you or anyone else that finds their way here:

I ran into the same problem with netifaces during installation and it took me a while to realize that I was missing the actual compile tool for VC++. Using the installer from https://visualstudio.microsoft.com/visual-cpp-build-tools/ and installing the component "Desktop development with C++" solved the issue for me.

**Comment by maayan-sh** [comment]
Thanks @erithacus-rubecula that's a good observation.
@RosadoJ - Installing python 3.9 and the Microsoft Visual C++ 14.0, should set up the ground for installing all the necessary modules. I recommend you to try again in a clean environment with all of these components.

**Comment by maayan-sh** [comment]
I’m closing the issue as it has been open for a while with suggested solutions and without further feedback. Please don’t hesitate to reach out or reopen the issue if any problem arises. Thanks!
